version: "3"
services:
  mariadb:
    image: mariadb
    restart: unless-stopped
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=true
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}

  influxdb:
    image: influxdb:2.0
    restart: unless-stopped
    volumes:
      - ./influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}

  django:
    image: solo5star/stcomputer-backend:0.1.2
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./media:/media
    command: /entrypoints/django.sh
    env_file:
      - .env
    environment:
      #- DJANGO_BIND_ADDRESS=0.0.0.0
      - DJANGO_PORT=8000
      - DJANGO_MEDIA_ROOT=/media/
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  celery-worker:
    image: solo5star/stcomputer-backend:0.1.2
    restart: unless-stopped
    volumes:
      - ./media:/media
    command: /entrypoints/celery-worker.sh
    env_file:
      - .env
    environment:
      - DJANGO_MEDIA_ROOT=/media/
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672

  celery-beat:
    image: solo5star/stcomputer-backend:0.1.2
    restart: unless-stopped
    volumes:
      - ./media:/media
    command: /entrypoints/celery-beat.sh
    env_file:
      - .env
    environment:
      - DJANGO_MEDIA_ROOT=/media/
      - MARIADB_HOST=mariadb
      - MARIADB_PORT=3306
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_PORT=8086
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
