# Generated by Django 3.2.8 on 2021-10-08 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadThumbnailQueuedProductSpec',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='products.productspec')),
                ('thumbnail_url', models.URLField()),
            ],
        ),
    ]
